#!/usr/bin/sh

wal -R
. "${HOME}/.cache/wal/colors.sh"

sxhkd &
nm-applet &
polybar desktopbarleft &
polybar desktopbarmid &
polybar desktopbarright &
pulseaudio --kill
pulseaudio --start &


bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

bspc config presel_feedback_color "$color1"

bspc monitor DVI-D-0 -d I II III
bspc monitor DP-2 -d code firefox VI VII
bspc monitor HDMI-0 -d IIX music discord

bspc config border_width    	5
bspc config window_gap      	25
bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config top_padding 	20
bspc config bottom_padding 	20
bspc config left_padding	20
bspc config right_padding	20

bspc config focus_follows_pointer true

bspc rule -a Firefox desktop=firefox follow=on
bspc rule -a Emacs desktop=code folllow=on state=tiled
bspc rule -a Discord desktop=discord follow=off
bspc rule -a Spotify desktop=music follow=off state=tiled
